// <auto-generated />
using System;
using BlacklistedMobiles.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlacklistedMobiles.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240327043606_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("BlacklistedMobiles.API.Models.Domain.Municipality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15747a09-bfed-4449-8f90-44dc56d63fa6"),
                            Code = "1201",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5597),
                            Name = "Calixto García",
                            ProvinceId = new Guid("a5fcb845-c248-4a3f-a796-5d7d1a6b9d2c")
                        },
                        new
                        {
                            Id = new Guid("5b174629-51d9-4ce0-9627-810bf332ba7a"),
                            Code = "1202",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5605),
                            Name = "Gibara",
                            ProvinceId = new Guid("a5fcb845-c248-4a3f-a796-5d7d1a6b9d2c")
                        },
                        new
                        {
                            Id = new Guid("b7f763f8-d085-4f2f-a785-b212e5fd8896"),
                            Code = "1203",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5610),
                            Name = "Banes",
                            ProvinceId = new Guid("a5fcb845-c248-4a3f-a796-5d7d1a6b9d2c")
                        },
                        new
                        {
                            Id = new Guid("98c4aa76-66a0-4a47-882c-3f08ba50ecb2"),
                            Code = "1204",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5615),
                            Name = "Rafael Freyre",
                            ProvinceId = new Guid("a5fcb845-c248-4a3f-a796-5d7d1a6b9d2c")
                        },
                        new
                        {
                            Id = new Guid("22f3dd42-0337-46fe-b40e-39481ed6b9e9"),
                            Code = "1205",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5619),
                            Name = "Moa",
                            ProvinceId = new Guid("a5fcb845-c248-4a3f-a796-5d7d1a6b9d2c")
                        },
                        new
                        {
                            Id = new Guid("a62128fb-bbe1-477f-b3d7-c2dd91579ca4"),
                            Code = "1206",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5624),
                            Name = "Holguín",
                            ProvinceId = new Guid("a5fcb845-c248-4a3f-a796-5d7d1a6b9d2c")
                        });
                });

            modelBuilder.Entity("BlacklistedMobiles.API.Models.Domain.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f39e8e2-6ee0-468d-b0a2-48c57b36b4c3"),
                            Code = "01",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5492),
                            Name = "Pinar del Río"
                        },
                        new
                        {
                            Id = new Guid("70d2370c-e3af-4158-b3d7-2e47fd621565"),
                            Code = "02",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5501),
                            Name = "La Habana"
                        },
                        new
                        {
                            Id = new Guid("b0950c26-c31f-4d91-84d7-36ad77701d4e"),
                            Code = "03",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5504),
                            Name = "Artemisa"
                        },
                        new
                        {
                            Id = new Guid("d65aedf0-454f-477e-922c-60531a2035d3"),
                            Code = "04",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5508),
                            Name = "Mayabeque"
                        },
                        new
                        {
                            Id = new Guid("4d3ec422-6b51-4b6f-9adc-7153f768c080"),
                            Code = "05",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5511),
                            Name = "Matanzas"
                        },
                        new
                        {
                            Id = new Guid("290ce103-1278-4fc4-b724-7d6c0ff12254"),
                            Code = "06",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5518),
                            Name = "Cienfuegos"
                        },
                        new
                        {
                            Id = new Guid("1064bae6-4902-4bf6-9431-1a7e1726e19d"),
                            Code = "07",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5521),
                            Name = "Villa Clara"
                        },
                        new
                        {
                            Id = new Guid("7fa460f3-1aae-40ad-9fb5-b53251a83040"),
                            Code = "08",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5525),
                            Name = "Sancti Spíritus"
                        },
                        new
                        {
                            Id = new Guid("f5c7be86-963a-4a02-a79f-49b925be6c00"),
                            Code = "09",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5528),
                            Name = "Ciego de Ávila"
                        },
                        new
                        {
                            Id = new Guid("75362065-425e-40f9-b5ba-c180ffa989c9"),
                            Code = "10",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5533),
                            Name = "Camagüey"
                        },
                        new
                        {
                            Id = new Guid("9e9779e6-680e-4588-ae57-b21778f4ca09"),
                            Code = "11",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5536),
                            Name = "Las Tunas"
                        },
                        new
                        {
                            Id = new Guid("a5fcb845-c248-4a3f-a796-5d7d1a6b9d2c"),
                            Code = "12",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5539),
                            Name = "Holguín"
                        },
                        new
                        {
                            Id = new Guid("fc7926b0-fc85-4e52-96b8-87590d1efba9"),
                            Code = "13",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5543),
                            Name = "Granma"
                        },
                        new
                        {
                            Id = new Guid("e183277f-03e4-4248-be3f-318e89eb77fa"),
                            Code = "14",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5546),
                            Name = "Santiago de Cuba"
                        },
                        new
                        {
                            Id = new Guid("3455b71f-6e0b-4416-841d-56c1745529dc"),
                            Code = "15",
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5550),
                            Name = "Guantánamo"
                        });
                });

            modelBuilder.Entity("BlacklistedMobiles.API.Models.Domain.Trademark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trademarks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42d0384a-cc80-4b54-9ecc-dc2a6244f9da"),
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5256),
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("649cfe5e-2c2c-4976-ae8b-7f938acc2207"),
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5336),
                            Name = "Huawei"
                        },
                        new
                        {
                            Id = new Guid("9a8db676-d198-43ad-b963-6e50dea2dfdd"),
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5342),
                            Name = "LG"
                        },
                        new
                        {
                            Id = new Guid("45eac17f-f06d-4235-a1fa-74164a015a67"),
                            CreatedAt = new DateTime(2024, 3, 27, 0, 36, 5, 486, DateTimeKind.Local).AddTicks(5345),
                            Name = "Xiaomi"
                        });
                });

            modelBuilder.Entity("BlacklistedMobiles.API.Models.Domain.Municipality", b =>
                {
                    b.HasOne("BlacklistedMobiles.API.Models.Domain.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });
#pragma warning restore 612, 618
        }
    }
}
